# Generated by Django 4.1.4 on 2023-01-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_hospital_healthfaculty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='HealthFaculty',
            new_name='health_faculty',
        ),
    ]
