# Generated by Django 4.1.4 on 2023-01-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_processing_healthfaculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processing',
            old_name='HealthFaculty',
            new_name='healthFaculty',
        ),
    ]
