# Generated by Django 4.1.4 on 2023-01-07 22:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patriarch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthClass',
            fields=[
                ('Class', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 3')], max_length=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Patriarch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patriarch')),
            ],
        ),
    ]
