# Generated by Django 4.1.4 on 2023-01-07 23:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_healthfaculty_profile_health_faculty'),
        ('patients', '0007_healthclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('exams', models.TextField()),
                ('medecines', models.TextField()),
                ('procedures', models.TextField()),
                ('date', models.DateTimeField()),
                ('others', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
        migrations.AddField(
            model_name='bill',
            name='consultation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='exams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='medecines',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='others',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='procedures',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.bill'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='health_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.healthfaculty'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.family'),
        ),
    ]
