# Generated by Django 4.1.4 on 2023-01-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_bill_date_alter_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='consultation',
            new_name='consultation_fee',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='exams',
            new_name='exams_fee',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='medecines',
            new_name='medecines_fee',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='others',
            new_name='others_fee',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='procedures',
            new_name='procedures_fee',
        ),
    ]
