# Generated by Django 4.1.4 on 2023-01-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_rename_consultation_bill_consultation_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Bill',
            new_name='bill',
        ),
    ]
