# Generated by Django 4.1.4 on 2023-01-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_healthfaculty_profile_health_faculty'),
        ('patients', '0011_rename_bill_invoice_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthclass',
            name='Class',
            field=models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='processing',
            unique_together={('patient', 'healthFaculty')},
        ),
    ]
