# Generated by Django 4.1.4 on 2023-01-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_healthclass_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patriarch',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
